FROM golang:1.17.5

WORKDIR /usr/src/app

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /go/bin/app

EXPOSE 8000

ENTRYPOINT [ "/go/bin/app" ]