version: '3'
services:
  go:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/workspace/app/backend
      - /usr/share/zoneinfo/Asia/Tokyo:/etc/localtime
    working_dir: /workspace/app/backend
    tty: true
    env_file:
      - .env
    depends_on:
      - db
  db:
    build: ./db
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER_NAME}
      - MYSQL_PASSWORD=${DATABASE_USER_PASSWORD}
    ports:
      - "3306:3306"
